name: Build for Windows

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Configure and Build
      shell: cmd
      run: |
        :: Inicializar el entorno de Visual Studio
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" || ^
        call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
        
        :: Patch: Comentar la línea que añade el subdirectorio 'tests' en el archivo principal
        :: Esto evita el error de CUnit sin borrar la carpeta ni romper la estructura
        powershell -Command "(Get-Content CMakeLists.txt) -replace 'add_subdirectory\(tests\)', '# add_subdirectory(tests)' | Set-Content CMakeLists.txt"
        
        :: Configurar con CMake
        cmake -S examples/client/udp -B build-client-udp -GNinja
        
        :: Compilar
        cmake --build build-client-udp

    - name: Upload lwm2mclient binary
      uses: actions/upload-artifact@v4
      with:
        name: lwm2mclient-windows
        path: build-client-udp/lwm2mclient.exe
        if-no-files-found: error
